### ISSUE TITLE
Error has occurred while trying to sign in

### ISSUE THREAD

**Issue by dmklementiev-zz** [microsoft/Broadcast-Development-Kit-Web-UI#26]
When I try to run Broadcast-Development-Kit-Web-UI solution as described in[ this document](https://github.com/microsoft/Broadcast-Development-Kit-Web-UI/blob/main/docs/how-to-run-the-solution-locally/README.md) the login screen shows up after I run "npm run start".  Just clicking on the "Login to your account" button causing the following error message:

![image](https://user-images.githubusercontent.com/17224782/132143825-05c7f6d2-de95-4a0a-b1b3-d8b00f76ec2c.png)

Trying to navigate to localhost:3000 in "In Private" doesn't change the behavior 

Question 1: How to fix this
Question 2: Do I need to have an MSA account to sign in to run this sample?

**Comment by dcherubini** [comment]
Please double check that the settings in your `config.json` file match the ones in the [Configure the solution](https://github.com/microsoft/Broadcast-Development-Kit-Web-UI/blob/main/docs/how-to-run-the-solution-locally/README.md#configure-the-solution) section. When running locally, you should have the `DISABLE_AUTHENTICATION` flag enabled to skip the authentication flow in the UI, unless you are trying to configure the solution to run with authentication "on" in your local machine.

The [backend should also be configured](https://github.com/microsoft/Broadcast-Development-Kit/tree/main/docs/how-to-run-the-solution-locally#configure-the-backend-solution-to-run-locally) to run in the `local` environment.

![image](https://user-images.githubusercontent.com/3065007/132248768-329fc076-2cc1-43ba-82fa-10959165d472.png)

**Comment by dmklementiev-zz** [comment]
Sorry, my bad, the json I had was malformed. I can bypass authentication after fixing it.  Now when I try to join the meeting, the status changes to Establishing and then to terminated.

![image](https://user-images.githubusercontent.com/17224782/132261842-f4d2a765-e40f-42ff-a29d-8a7a3ee79784.png)

I see status change in the BotService as well.  What would be the best way to investigate why the bot cannot connect a meeting?

Also please let me know if you'd like me to close this issue and open a new one for the latter problem.

**Comment by dcherubini** [comment]
When the status changes from **Establishing** to **Terminated** it usually means that the Graph API was not able to complete the handshake with the BotService, which is needed to obtain the information of the meeting. When running the solution locally this can be caused by problems related to the Ngrok configuration (e.g. Ngrok was not running, the `appSettings` file was not updated with the latest parameters that Ngrok is using, etc.). Please double check that:

- The BotService's `appSettings.local.json` file matches with the values shown by Ngrok as explained in [this document](https://github.com/microsoft/Broadcast-Development-Kit/tree/main/docs/how-to-run-the-solution-locally#configure-botservice). Note that you need to update these settings each time you run Ngrok.
-  The [SSL certificate](https://github.com/microsoft/Broadcast-Development-Kit/blob/main/docs/common/install_domain_certificate.md) you obtained was properly installed in your local machine.

Since this problem is more related to the backend of the solution, you can create a new issue in the [backend repository](https://github.com/microsoft/Broadcast-Development-Kit) if you keep seeing these problems.

**Comment by dmklementiev-zz** [comment]
Closing this issue and opening a new one in backend repository
